/**
 * @packbreaker/content — schemas
 *
 * Verbatim port of content-schemas.ts §§ 1–11, 16, 17 (v0.1, locked 2026-04-25,
 * additive bump 2026-04-27). Authoritative type system for items, recipes,
 * classes, relics, contracts, status, bag, run, and combat. Pure types +
 * constants. Sim package consumes these types but must not read
 * `Item.passiveStats` (lint-enforced — see tooling/eslint-config/index.cjs).
 *
 * Source-of-truth for the design intent and prose comments: /content-schemas.ts
 * at the repo root. Do not edit this file in isolation — sync changes both ways
 * during M1.x. After M1 graybox, content-schemas.ts is retired and this file
 * becomes canonical.
 */


// ─────────────────────────────────────────────────────────────────────────────
// § 1 — COMMON PRIMITIVES
// ─────────────────────────────────────────────────────────────────────────────

/** Branded primitive helper. */
export type Brand<T, B extends string> = T & { readonly __brand: B };

/** ID brands. Compile-time safety against mixing IDs across categories. */
export type ItemId      = Brand<string, 'ItemId'>;
export type RecipeId    = Brand<string, 'RecipeId'>;
export type RelicId     = Brand<string, 'RelicId'>;
export type ContractId  = Brand<string, 'ContractId'>;
export type ClassId     = Brand<string, 'ClassId'>;
export type GhostId     = Brand<string, 'GhostId'>;
export type RunId       = Brand<string, 'RunId'>;
export type PlacementId = Brand<string, 'PlacementId'>;

/** 32-bit seed value. Consumed by mulberry32 in packages/sim/src/rng.ts. */
export type SimSeed = Brand<number, 'SimSeed'>;

/** ISO 8601 timestamp string. Metadata only — never read inside the sim. */
export type IsoTimestamp = Brand<string, 'IsoTimestamp'>;

/** ISO date string (YYYY-MM-DD). Used for daily contracts. */
export type IsoDate = Brand<string, 'IsoDate'>;

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

/** Open-vocabulary tags. Used for adjacency matching, recipe inputs, class affinity. */
export type ItemTag =
  | 'weapon' | 'armor' | 'consumable' | 'gem' | 'tool' | 'plant'
  | 'metal' | 'fire' | 'ice' | 'poison' | 'gold' | 'food';
  // Extensible — never branch on string literals outside content data.

/** Round number, 1-indexed, max 11 in M1 (10 standard + 1 boss). */
export type RoundNumber = number;


// ─────────────────────────────────────────────────────────────────────────────
// § 2 — GEOMETRY
// ─────────────────────────────────────────────────────────────────────────────

export interface BagDimensions {
  readonly width: number;  // M1 default: 6
  readonly height: number; // M1 default: 4
}

/** Cell coordinate in bag space. (0,0) = top-left. */
export interface CellCoord {
  readonly col: number;
  readonly row: number;
}

/** Quarter-turns. Item behavior does not change with rotation in M1 (gdd.md § 3). */
export type Rotation = 0 | 90 | 180 | 270;

/**
 * An item's footprint, expressed as cells relative to its anchor (0,0).
 * The anchor is always the cell at the bounding-box top-left when at Rotation 0.
 */
export type ItemShape = ReadonlyArray<CellCoord>;


// ─────────────────────────────────────────────────────────────────────────────
// § 3 — ITEM SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

/** Selector for the target of an effect during combat. */
export type TargetSelector =
  | 'self'
  | 'opponent'
  | 'self_random_item'
  | 'opp_random_item';

export type StatusType = 'burn' | 'poison' | 'stun';

export type BuffableStat = 'damage' | 'cooldown_pct' | 'trigger_chance_pct';

/**
 * Passive stats — applied by the run controller BEFORE calling simulateCombat.
 * Sim never reads this field. Used for max HP, gold per round, and future
 * base damage modifiers that the sim shouldn't have to interpret.
 */
export interface PassiveStats {
  readonly maxHpBonus?: number;
  readonly bonusBaseDamage?: number;
  readonly goldPerRound?: number;
}

/** Effect primitives. Discriminated by `type`. (gdd.md § 5) */
export type Effect =
  | {
      readonly type: 'damage';
      readonly amount: number;
      readonly target: TargetSelector;
    }
  | {
      readonly type: 'heal';
      readonly amount: number;
      readonly target: TargetSelector;
    }
  | {
      readonly type: 'apply_status';
      readonly status: StatusType;
      readonly stacks: number;
      readonly durationTicks?: number;
      readonly target: TargetSelector;
    }
  | {
      readonly type: 'add_gold';
      readonly amount: number;
    }
  | {
      readonly type: 'buff_adjacent';
      readonly stat: BuffableStat;
      readonly amount: number;
      readonly durationTicks?: number;
    }
  | {
      readonly type: 'summon_temp_item';
      readonly itemId: ItemId;
      readonly durationTicks: number;
    };

/**
 * Trigger primitives. Each carries the effects to fire.
 *
 * `maxTriggersPerCombat` (optional, all variants): caps how many times the
 * trigger fires within a single combat. Omit for unlimited (default). Use 1
 * for single-use items (Bandage), small N for capped items (Bread). Sim
 * resets the per-trigger counter at combat start.
 */
export type Trigger =
  | {
      readonly type: 'on_round_start';
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    }
  | {
      readonly type: 'on_cooldown';
      readonly cooldownTicks: number;
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    }
  | {
      readonly type: 'on_hit';
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    }
  | {
      readonly type: 'on_taken_damage';
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    }
  | {
      readonly type: 'on_adjacent_trigger';
      readonly matchTags?: ReadonlyArray<ItemTag>;
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    }
  | {
      readonly type: 'on_low_health';
      readonly thresholdPct: number;
      readonly effects: ReadonlyArray<Effect>;
      readonly maxTriggersPerCombat?: number;
    };

/** A canonical item definition. Static, content-authored, immutable. */
export interface Item {
  readonly id: ItemId;
  readonly name: string;
  readonly rarity: Rarity;
  readonly classAffinity: ClassId | null;
  readonly shape: ItemShape;
  readonly tags: ReadonlyArray<ItemTag>;
  readonly cost: number;
  readonly triggers: ReadonlyArray<Trigger>;
  readonly passiveStats?: PassiveStats;
  readonly artId: string;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 4 — RECIPE SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface RecipeInputCell {
  readonly relativeCol: number;
  readonly relativeRow: number;
  readonly itemId: ItemId;
}

export interface Recipe {
  readonly id: RecipeId;
  readonly name: string;
  readonly inputs: ReadonlyArray<RecipeInputCell>;
  readonly output: ItemId;
  readonly rotationLocked: boolean;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 5 — CLASS SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface ClassPassive {
  readonly description: string;
  readonly recipeBonusPct?: number;
  readonly firstRecipeFreeAction?: boolean;
  readonly bonusBaseDamage?: number;
  readonly bonusGoldOnWin?: number;
}

export interface Class {
  readonly id: ClassId;
  readonly displayName: string;
  readonly passive: ClassPassive;
  readonly affinityTags: ReadonlyArray<ItemTag>;
  readonly starterRelicPool: ReadonlyArray<RelicId>;
  readonly portraitArtId: string;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 6 — RELIC SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export type RelicSlot = 'starter' | 'mid' | 'boss';

export interface RelicModifiers {
  readonly extraRerollsPerRound?: number;
  readonly rerollCostDelta?: number;
  readonly itemCostDelta?: number;
  readonly recipeBonusPct?: number;
  readonly bonusBaseDamage?: number;
  readonly lifestealPct?: number;
  readonly bonusStartingGold?: number;
  readonly extraShopSlots?: number;
  readonly bonusHearts?: number;
}

export interface Relic {
  readonly id: RelicId;
  readonly name: string;
  readonly description: string;
  readonly classAffinity: ClassId | null;
  readonly slot: RelicSlot;
  readonly modifiers: RelicModifiers;
  readonly artId: string;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 7 — STATUS SYSTEM
// ─────────────────────────────────────────────────────────────────────────────

export interface ActiveStatus {
  readonly type: StatusType;
  readonly stacks: number;
  /** Remaining ticks. -1 = full-combat duration. 0 = expired. */
  readonly remainingTicks: number;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 8 — CONTRACT & RULESET
// ─────────────────────────────────────────────────────────────────────────────

export interface Ruleset {
  readonly bagDimensions: BagDimensions;
  readonly maxRounds: number;
  readonly bossRound: number;
  readonly startingHearts: number;
  readonly shopSize: number;
  readonly baseGoldPerRound: number;
  readonly goldStepRounds: number;
  readonly goldStepAmount: number;
  readonly rerollCostStart: number;
  readonly rerollCostIncrement: number;
  readonly itemCostMultiplierBp: number;
  readonly winBonusGold: number;
  readonly sellRecoveryBp: number;
  readonly mutators: ReadonlyArray<ContractMutator>;
}

export type ContractMutator =
  | { readonly type: 'adjacent_double' }
  | { readonly type: 'recipe_discount'; readonly amount: number }
  | { readonly type: 'no_rerolls' }
  | {
      readonly type: 'boss_only';
      readonly hpOverride?: number;
      readonly damageBonus?: number;
      readonly lifestealPctBonus?: number;
    };

export interface Contract {
  readonly id: ContractId;
  readonly name: string;
  readonly description: string;
  readonly ruleset: Ruleset;
  readonly isDaily: boolean;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 9 — BAG STATE
// ─────────────────────────────────────────────────────────────────────────────

export interface BagPlacement {
  readonly placementId: PlacementId;
  readonly itemId: ItemId;
  readonly anchor: CellCoord;
  readonly rotation: Rotation;
}

export interface BagState {
  readonly dimensions: BagDimensions;
  readonly placements: ReadonlyArray<BagPlacement>;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 10 — RUN STATE
// ─────────────────────────────────────────────────────────────────────────────

export interface RelicSlots {
  readonly starter: RelicId | null;
  readonly mid: RelicId | null;
  readonly boss: RelicId | null;
}

export type RoundOutcome = 'win' | 'loss';

export interface RunHistoryEntry {
  readonly round: RoundNumber;
  readonly outcome: RoundOutcome;
  readonly damageDealt: number;
  readonly damageTaken: number;
  readonly goldEarnedThisRound: number;
  readonly opponentGhostId: GhostId | null;
}

export interface ShopState {
  readonly slots: ReadonlyArray<ItemId>;
  readonly purchased: ReadonlyArray<number>;
  readonly rerollsThisRound: number;
}

export type RunOutcome = 'in_progress' | 'won' | 'eliminated' | 'abandoned';

export interface RunState {
  readonly runId: RunId;
  readonly seed: SimSeed;
  readonly classId: ClassId;
  readonly contractId: ContractId;
  readonly ruleset: Ruleset;
  readonly startedAt: IsoTimestamp;
  readonly hearts: number;
  readonly gold: number;
  readonly currentRound: RoundNumber;
  readonly bag: BagState;
  readonly relics: RelicSlots;
  readonly shop: ShopState;
  readonly trophiesAtStart: number;
  readonly history: ReadonlyArray<RunHistoryEntry>;
  readonly outcome: RunOutcome;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 11 — COMBAT
// ─────────────────────────────────────────────────────────────────────────────

export type EntityRef = 'player' | 'ghost';

export interface ItemRef {
  readonly side: EntityRef;
  readonly placementId: PlacementId;
}

export interface Combatant {
  readonly bag: BagState;
  readonly relics: RelicSlots;
  readonly classId: ClassId;
  readonly startingHp: number;
}

export interface CombatInput {
  readonly seed: SimSeed;
  readonly player: Combatant;
  readonly ghost: Combatant;
}

export type CombatOutcome = 'player_win' | 'ghost_win' | 'draw';

export type CombatEvent =
  | {
      readonly tick: number;
      readonly type: 'combat_start';
      readonly playerHp: number;
      readonly ghostHp: number;
    }
  | {
      readonly tick: number;
      readonly type: 'item_trigger';
      readonly source: ItemRef;
      readonly trigger: Trigger['type'];
    }
  | {
      readonly tick: number;
      readonly type: 'damage';
      readonly source: ItemRef;
      readonly target: EntityRef;
      readonly amount: number;
      readonly remainingHp: number;
    }
  | {
      readonly tick: number;
      readonly type: 'heal';
      readonly source: ItemRef;
      readonly target: EntityRef;
      readonly amount: number;
      readonly newHp: number;
    }
  | {
      readonly tick: number;
      readonly type: 'status_apply';
      readonly source: ItemRef;
      readonly target: EntityRef;
      readonly status: StatusType;
      readonly stacks: number;
    }
  | {
      readonly tick: number;
      readonly type: 'status_tick';
      readonly target: EntityRef;
      readonly status: StatusType;
      readonly damage: number;
      readonly remainingHp: number;
    }
  | {
      readonly tick: number;
      readonly type: 'buff_apply';
      readonly source: ItemRef;
      readonly target: ItemRef;
      readonly stat: BuffableStat;
      readonly amount: number;
    }
  | {
      readonly tick: number;
      readonly type: 'combat_end';
      readonly outcome: CombatOutcome;
      readonly finalHp: { readonly player: number; readonly ghost: number };
    };

export interface CombatResult {
  readonly events: ReadonlyArray<CombatEvent>;
  readonly outcome: CombatOutcome;
  readonly finalHp: { readonly player: number; readonly ghost: number };
  readonly endedAtTick: number;
}


// ─────────────────────────────────────────────────────────────────────────────
// § 16 — DEFAULTS & CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────

/** Sim resolution: 10 ticks per simulated second. (tech-architecture.md § 4.1) */
export const TICKS_PER_SECOND = 10 as const;

/** Hard limit on combat duration to prevent infinite loops. */
export const MAX_COMBAT_TICKS = 600;

/** Base HP for player and ghost. Modified by passives + relics + class.
 *  Boss overrides via ContractMutator['boss_only'].hpOverride. */
export const BASE_COMBATANT_HP = 30;

/** Status stack caps. Sim enforces these in packages/sim/src/status.ts. */
export const STATUS_STACK_CAPS: Readonly<Record<StatusType, number>> = {
  burn: 10,
  poison: 10,
  stun: 1,
};

/** Default ruleset baseline. Contracts and relics layer modifications on top. */
export const DEFAULT_RULESET: Ruleset = {
  bagDimensions: { width: 6, height: 4 },
  maxRounds: 11,
  bossRound: 11,
  startingHearts: 3,
  shopSize: 5,
  baseGoldPerRound: 4,
  goldStepRounds: 3,
  goldStepAmount: 1,
  rerollCostStart: 1,
  rerollCostIncrement: 1,
  itemCostMultiplierBp: 10000,
  winBonusGold: 1,
  sellRecoveryBp: 5000,
  mutators: [],
};

/** Rarity bands. Pool weights are integers summing to 100. (gdd.md § 5) */
export const RARITY_POOL_WEIGHT: Readonly<Record<Rarity, number>> = {
  common: 60,
  uncommon: 25,
  rare: 10,
  epic: 4,
  legendary: 1,
};

export const RARITY_DEFAULT_COST: Readonly<Record<Rarity, number>> = {
  common: 3,
  uncommon: 5,
  rare: 7,
  epic: 9,
  legendary: 12,
};

/** Power budget per rarity — design-time only, never enters the sim. */
export const RARITY_POWER_BUDGET: Readonly<Record<Rarity, number>> = {
  common: 1.0,
  uncommon: 1.6,
  rare: 2.4,
  epic: 3.5,
  legendary: 5.0,
};

/** Round → highest rarity available in the shop. (gdd.md § 4) */
export const RARITY_GATE_BY_ROUND: ReadonlyArray<Rarity> = [
  'common',    // round 1
  'common',    // round 2
  'common',    // round 3
  'uncommon',  // round 4
  'uncommon',  // round 5
  'uncommon',  // round 6
  'rare',      // round 7
  'rare',      // round 8
  'rare',      // round 9
  'epic',      // round 10
  'legendary', // round 11 (boss reward)
];


// ─────────────────────────────────────────────────────────────────────────────
// § 17 — TYPE GUARDS & UTILITIES
// ─────────────────────────────────────────────────────────────────────────────

export const isRarity = (v: unknown): v is Rarity =>
  v === 'common' || v === 'uncommon' || v === 'rare' || v === 'epic' || v === 'legendary';

export const isRunInProgress = (run: RunState): boolean =>
  run.outcome === 'in_progress';

export const isCombatTerminal = (
  e: CombatEvent,
): e is Extract<CombatEvent, { type: 'combat_end' }> =>
  e.type === 'combat_end';

/** Constructors for branded IDs. Centralized — never call `as ItemId` ad-hoc. */
export const ItemId      = (s: string): ItemId      => s as ItemId;
export const RecipeId    = (s: string): RecipeId    => s as RecipeId;
export const RelicId     = (s: string): RelicId     => s as RelicId;
export const ContractId  = (s: string): ContractId  => s as ContractId;
export const ClassId     = (s: string): ClassId     => s as ClassId;
export const GhostId     = (s: string): GhostId     => s as GhostId;
export const RunId       = (s: string): RunId       => s as RunId;
export const PlacementId = (s: string): PlacementId => s as PlacementId;
export const SimSeed     = (n: number): SimSeed     => n as SimSeed;
export const IsoTimestamp = (s: string): IsoTimestamp => s as IsoTimestamp;
export const IsoDate      = (s: string): IsoDate      => s as IsoDate;
